select * from customer;

-- Q1:what is total revenue generated by male vs female customer?
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender;
-- Q2:Which customers used a discount but still spend more than average purchase amount?
SELECT customer_id
FROM customer
WHERE discount_applied IS NOT NULL
AND purchase_amount > (
    SELECT AVG(purchase_amount)
    FROM customer
);
-- Q3:Which are the top 5 products with the highest average review rating
select item_purchased, AVG(review_rating)
from customer
group by item_purchased
order by AVG(review_rating) DESC
limit 5;
-- Q4:Compare the average Purchase amount between standard and express shipping
select shipping_type, AVG(purchase_amount)
from customer
where shipping_type in ("Standard","Express")
group by shipping_type;
-- Q5: Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
select subscription_status, sum(purchase_amount), AVG(purchase_amount)
from customer
where subscription_status is not false or subscription_status is not true
group by subscription_status;
-- Q6: Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
-- Q7: Segment customer into New, Returning, and loyal based on their total number of previous purchases, and show the count of segment
SELECT 
    customer_id,
    previous_purchases,
    CASE 
        WHEN previous_purchases <= 10 THEN 'New'
        WHEN previous_purchases <= 30 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
FROM customer;

-- Q8: What are the top 3 most purchased product within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
-- Q9: Are customers who are repeat buyers (more than 5 previous purchases) alo likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;